# CA1 - Data Visualisation and Communication 
Lecturer Name: Taufique Ahmed

## Barbara Souza 2023059
### GitHub Link
https://github.com/BarbSouza/data-visualisation.git
### Video Link
https://drive.google.com/drive/folders/19yAy5wb7vKj4OV-kTpZ81bX17kZqhXc9?usp=drive_link

In [8]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

dataset =  pd.read_excel("all_data_M_2023.xlsx")

## Dataset Descr

In [15]:
dataset_description = pd.read_excel("all_data_M_2023.xlsx", sheet_name="Field Descriptions")

In [29]:
dataset_description

,May 2023 OEWS Estimates,Unnamed: 1,Unnamed: 2
0,NaN,NaN,NaN
1,Occupational Employment and Wage Statistics (O...,NaN,NaN
2,"Bureau of Labor Statistics, Department of Labor",NaN,NaN
3,website: www.bls.gov/oes,NaN,NaN
4,email: oewsinfo@bls.gov,NaN,NaN
5,NaN,NaN,NaN
6,Not all fields are available for every type of...,NaN,NaN
7,NaN,NaN,NaN
8,Field,Field Description,NaN
9,area,"U.S. (99), state FIPS code, Metropolitan Stati...",NaN
10,area_title,Area name,NaN
11,area_type,Area type: 1= U.S.; 2= State; 3= U.S. Territor...,NaN
12,prim_state,"The primary state for the given area. ""US"" is ...",NaN
13,naics,North American Industry Classification System ...,NaN
14,naics_title,North American Industry Classification System ...,NaN
15,i_group,Industry level. Indicates cross-industry or NA...,NaN
16,own_code,Ownership type: 1= Federal Government; 2= Stat...,NaN
17,occ_code,The 6-digit Standard Occupational Classificati...,NaN
18,occ_title,SOC title or OEWS-specific title for the occup...,NaN
19,o_group,"SOC occupation level. For most occupations, th...",.
20,tot_emp,Estimated total employment rounded to the near...,NaN
21,emp_prse,Percent relative standard error (PRSE) for the...,NaN
22,jobs_1000,The number of jobs (employment) in the given o...,.
23,loc quotient,The location quotient represents the ratio of ...,NaN
24,pct_total,Percent of industry employment in the given oc...,.
25,pct_rpt,Percent of establishments reporting the given ...,NaN
26,h_mean,Mean hourly wage,NaN
27,a_mean,Mean annual wage,NaN
28,mean_prse,Percent relative standard error (PRSE) for the...,NaN
29,h_pct10,Hourly 10th percentile wage,NaN
30,h_pct25,Hourly 25th percentile wage,NaN
31,h_median,Hourly median wage (or the 50th percentile),NaN
32,h_pct75,Hourly 75th percentile wage,NaN
33,h_pct90,Hourly 90th percentile wage,NaN
34,a_pct10,Annual 10th percentile wage,NaN
35,a_pct25,Annual 25th percentile wage,NaN
36,a_median,Annual median wage (or the 50th percentile),NaN
37,a_pct75,Annual 75th percentile wage,NaN
38,a_pct90,Annual 90th percentile wage,NaN
39,annual,"Contains ""TRUE"" if only annual wages are relea...",.
40,hourly,"Contains ""TRUE"" if only hourly wages are relea...",.
41,NaN,NaN,NaN
42,Notes:,NaN,NaN
43,* = indicates that a wage estimate is not ava...,NaN,NaN
44,** = indicates that an employment estimate is...,NaN,NaN
45,# = indicates a wage equal to or greater than...,NaN,NaN
46,~ =indicates that the percent of establishment...,NaN,NaN

## Dataset info

In [9]:
dataset.head(10)

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,23.11,37.01,58.4,29050,35660,48060,76980,121470,NaN,NaN
1,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,56.19,81.29,111.36,54550,78330,116880,169090,231620,NaN,NaN
2,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1000,Top Executives,...,49.74,79.57,#,46400,66170,103460,165500,#,NaN,NaN
3,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1010,Chief Executives,...,99.37,#,#,80000,130840,206680,#,#,NaN,NaN
4,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,99.37,#,#,80000,130840,206680,#,#,NaN,NaN
5,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1020,General and Operations Managers,...,48.69,77.06,111.59,46340,65180,101280,160290,232110,NaN,NaN
6,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1021,General and Operations Managers,...,48.69,77.06,111.59,46340,65180,101280,160290,232110,NaN,NaN
7,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1030,Legislators,...,*,*,*,21010,28810,47290,82200,129510,True,NaN
8,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1031,Legislators,...,*,*,*,21010,28810,47290,82200,129510,True,NaN
9,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-2000,"Advertising, Marketing, Promotions, Public Rel...",...,67.23,96.15,#,69170,99180,139850,199990,#,NaN,NaN

In [10]:
dataset.shape

(413327, 32)

rows x columns

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413327 entries, 0 to 413326
Data columns (total 32 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   AREA          413327 non-null  int64
 1   AREA_TITLE    413327 non-null  object
 2   AREA_TYPE     413327 non-null  int64
 3   PRIM_STATE    413327 non-null  object
 4   NAICS         413327 non-null  object
 5   NAICS_TITLE   413327 non-null  object
 6   I_GROUP       413327 non-null  object
 7   OWN_CODE      413327 non-null  int64
 8   OCC_CODE      413327 non-null  object
 9   OCC_TITLE     413327 non-null  object
 10  O_GROUP       413327 non-null  object
 11  TOT_EMP       413327 non-null  object
 12  EMP_PRSE      413327 non-null  object
 13  JOBS_1000     235826 non-null  object
 14  LOC_QUOTIENT  235826 non-null  object
 15  PCT_TOTAL     170470 non-null  object
 16  PCT_RPT       170470 non-null  object
 17  H_MEAN        413327 non-null  object
 18  A_MEAN        413327 non-null  object
 19  MEAN_PRSE     413327 non-null  object
 20  H_PCT10       413327 non-null  object
 21  H_PCT25       413327 non-null  object
 22  H_MEDIAN      413327 non-null  object
 23  H_PCT75       413327 non-null  object
 24  H_PCT90       413327 non-null  object
 25  A_PCT10       413327 non-null  object
 26  A_PCT25       413327 non-null  object
 27  A_MEDIAN      413327 non-null  object
 28  A_PCT75       413327 non-null  object
 29  A_PCT90       413327 non-null  object
 30  ANNUAL        16497 non-null   object
 31  HOURLY        755 non-null     object
dtypes: int64(3), object(29)
memory usage: 100.9+ MB

AREA, AREA_TYPE and OWN_CODE are numeric

In [12]:
dataset.isnull().sum()

AREA                 0
AREA_TITLE           0
AREA_TYPE            0
PRIM_STATE           0
NAICS                0
NAICS_TITLE          0
I_GROUP              0
OWN_CODE             0
OCC_CODE             0
OCC_TITLE            0
O_GROUP              0
TOT_EMP              0
EMP_PRSE             0
JOBS_1000       177501
LOC_QUOTIENT    177501
PCT_TOTAL       242857
PCT_RPT         242857
H_MEAN               0
A_MEAN               0
MEAN_PRSE            0
H_PCT10              0
H_PCT25              0
H_MEDIAN             0
H_PCT75              0
H_PCT90              0
A_PCT10              0
A_PCT25              0
A_MEDIAN             0
A_PCT75              0
A_PCT90              0
ANNUAL          396830
HOURLY          412572
dtype: int64

In [13]:
dataset.describe()

               AREA      AREA_TYPE       OWN_CODE
count  4.133270e+05  413327.000000  413327.000000
mean   3.784693e+05       2.766826     717.279984
std    1.135906e+06       1.780825     601.852382
min    1.000000e+00       1.000000       1.000000
25%    9.900000e+01       1.000000       5.000000
50%    9.900000e+01       2.000000    1235.000000
75%    3.710000e+04       4.000000    1235.000000
max    7.800001e+06       6.000000    1235.000000

## Cleaning

In [18]:
clean = dataset.copy()

In [21]:
dataset.value_counts("AREA_TYPE")

AREA_TYPE
1    177501
4    149591
6     48559
2     36643
3      1033
Name: count, dtype: int64

In [22]:
dataset.value_counts("I_GROUP")

I_GROUP
cross-industry               237229
4-digit                       83350
3-digit                       39097
sector                        16376
5-digit                       15518
4-digit, ownership             9856
cross-industry, ownership      5628
3-digit, ownership             4561
6-digit                        1712
Name: count, dtype: int64

In [24]:
dataset.value_counts("O_GROUP")

O_GROUP
detailed    306185
broad        62131
minor        23374
major        20601
total         1036
Name: count, dtype: int64

In [26]:
dataset.value_counts("OWN_CODE")

OWN_CODE
1235    237229
5       144246
235       8465
2         6419
3         6076
57        3689
123       3538
1         1878
58         960
59         827
Name: count, dtype: int64

In [27]:
dataset.value_counts("TOT_EMP")

TOT_EMP
40           19325
50           16872
60           14450
70           12537
**           11598
             ...
151853870        1
130039030        1
22068580         1
21814850         1
18533450         1
Name: count, Length: 12271, dtype: int64

In [28]:
dataset.value_counts("A_MEDIAN")

A_MEDIAN
*         5083
#         2391
41600      618
31200      584
52000      572
          ...
237780       1
236650       1
236920       1
238120       1
238160       1
Name: count, Length: 16664, dtype: int64

## Visualisation 1
1. What is the **objective** of the visualisation? (eg investigation, comparison etc)
2. **Why that visualisation type was chosen**? (categorical, numerical, relationships).  
3. **What you learned** about AI employment from the visualisation.

## Visualisation 2
1. What is the **objective** of the visualisation? (eg investigation, comparison etc)
2. **Why that visualisation type was chosen**? (categorical, numerical, relationships).  
3. **What you learned** about AI employment from the visualisation.

## Visualisation 3
1. What is the **objective** of the visualisation? (eg investigation, comparison etc)
2. **Why that visualisation type was chosen**? (categorical, numerical, relationships).  
3. **What you learned** about AI employment from the visualisation.

## Visualisation 4
1. What is the **objective** of the visualisation? (eg investigation, comparison etc)
2. **Why that visualisation type was chosen**? (categorical, numerical, relationships).  
3. **What you learned** about AI employment from the visualisation.

## Visualisation 5
1. What is the **objective** of the visualisation? (eg investigation, comparison etc)
2. **Why that visualisation type was chosen**? (categorical, numerical, relationships).  
3. **What you learned** about AI employment from the visualisation.

## Challenge
1. What is the **objective** of the visualisation? (eg investigation, comparison etc)
2. **Why that visualisation type was chosen**? (categorical, numerical, relationships).  
3. **What you learned** about AI employment from the visualisation.